services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autorecruiter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP port
    environment:
      MP_MAX_MESSAGES: 5000
    restart: unless-stopped

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: --dev --bind 0.0.0.0 --node-ip 127.0.0.1
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080" # Web Database GUI
    restart: unless-stopped

volumes:
  postgres_data:
