"""
What: Implements the Planner node for the Question-Maker Agent.
Why: Analyzes the job information and target difficulty to generate a structured set of interview goals.
Boundaries: Does not perform web retrieval, question generation, or validation.
"""

from typing import Dict, Any, List, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage

from apps.agents.shared.clients import gemini_flash_lite
from ..state import QuestionMakerState, InterviewGoal, PlannerMeta
from ..prompts.planner_prompt import (
    PLANNER_SYSTEM_INSTRUCTION,
    PLANNER_USER_TEMPLATE,
)

class PlannerOutput(BaseModel):
    """
    Structured output schema representing the list of goals and inferred difficulty generated by the planner.
    """
    meta: PlannerMeta = Field(description="Metadata including domain, resolved seniority, assumptions, and warnings.")
    goals: List[InterviewGoal] = Field(description="List of key evaluation goals for the technical interview.")
    inferred_difficulty: Literal["junior", "mid", "senior", "lead"] = Field(
        description="The difficulty level inferred or resolved for the job description. If a concrete difficulty was requested, this should match it."
    )

def plan_node(state: QuestionMakerState) -> Dict[str, Any]:
    """
    Parses job specifications and target seniority to create structured interview goals.
    
    Args:
        state: The current graph state containing job_name, job_description, difficulty, num_goals, total_duration_minutes.
        
    Returns:
        A state update dictionary containing the generated list of InterviewGoals and the resolved difficulty.
    """
    # 1. Extract inputs from state (with defaults)
    job_name = state.get("job_name", "Software Engineer")
    job_description = state.get("job_description", "")
    difficulty = state.get("difficulty", "infer")
    num_goals = state.get("num_goals", 5)
    total_duration_minutes = state.get("total_duration_minutes", 30)
    
    # 2. Format prompts
    system_instruction = PLANNER_SYSTEM_INSTRUCTION
    user_prompt = PLANNER_USER_TEMPLATE.format(
        difficulty=difficulty,
        num_goals=num_goals,
        total_duration_minutes=total_duration_minutes,
        job_name=job_name,
        job_description=job_description
    )
    
    # 3. Formulate standard LangChain message list
    messages = [
        SystemMessage(content=system_instruction),
        HumanMessage(content=user_prompt)
    ]
    
    # 4. Invoke LLM with structured output schema
    structured_llm = gemini_flash_lite.with_structured_output(PlannerOutput)
    response: PlannerOutput = structured_llm.invoke(messages)
    
    # 5. Normalize generated times to match total_duration_minutes perfectly
    total_generated_time = sum(g.interview_time_in_minute for g in response.goals)
    
    if total_generated_time != total_duration_minutes and total_generated_time > 0 and response.goals:
        scale = total_duration_minutes / total_generated_time
        
        # Scale and round each goal
        for g in response.goals:
            g.interview_time_in_minute = max(1, int(round(g.interview_time_in_minute * scale)))
            
        # Fix any rounding discrepancy by adjusting the largest goal
        new_total = sum(g.interview_time_in_minute for g in response.goals)
        diff = total_duration_minutes - new_total
        if diff != 0:
            # Find the goal with the largest time to absorb the difference
            largest_goal = max(response.goals, key=lambda g: g.interview_time_in_minute)
            # Ensure we don't reduce a goal below 1 minute
            if largest_goal.interview_time_in_minute + diff < 1:
                largest_goal.interview_time_in_minute = 1
            else:
                largest_goal.interview_time_in_minute += diff

    # 6. Return state updates, saving resolved/inferred difficulty and metadata back to state
    return {
        "goals": response.goals,
        "difficulty": response.inferred_difficulty,
        "meta": response.meta.model_dump()
    }
