"""
What: Implements the Planner node for the Question-Maker Agent.
Why: Analyzes the job information and target difficulty to generate a structured set of interview goals.
Boundaries: Does not perform web retrieval, question generation, or validation.
"""

from typing import Dict, Any, List, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage

from apps.agents.shared.clients import gemini_flash_lite
from ..state import QuestionMakerState, InterviewGoal
from ..prompts.planner_prompt import (
    PLANNER_SYSTEM_INSTRUCTION,
    PLANNER_USER_TEMPLATE,
)

class PlannerOutput(BaseModel):
    """
    Structured output schema representing the list of goals and inferred difficulty generated by the planner.
    """
    goals: List[InterviewGoal] = Field(description="List of key evaluation goals for the technical interview.")
    inferred_difficulty: Literal["junior", "mid", "senior", "lead"] = Field(
        description="The difficulty level inferred or resolved for the job description. If a concrete difficulty was requested, this should match it."
    )

def plan_node(state: QuestionMakerState) -> Dict[str, Any]:
    """
    Parses job specifications and target seniority to create structured interview goals.
    
    Args:
        state: The current graph state containing job_name, job_description, difficulty, num_goals, total_duration_minutes.
        
    Returns:
        A state update dictionary containing the generated list of InterviewGoals and the resolved difficulty.
    """
    # 1. Extract inputs from state (with defaults)
    job_name = state.get("job_name", "Software Engineer")
    job_description = state.get("job_description", "")
    difficulty = state.get("difficulty", "infer")
    num_goals = state.get("num_goals", 5)
    total_duration_minutes = state.get("total_duration_minutes", 30)
    
    # 2. Format prompts
    system_instruction = PLANNER_SYSTEM_INSTRUCTION
    user_prompt = PLANNER_USER_TEMPLATE.format(
        difficulty=difficulty,
        num_goals=num_goals,
        total_duration_minutes=total_duration_minutes,
        job_name=job_name,
        job_description=job_description
    )
    
    # 3. Formulate standard LangChain message list
    messages = [
        SystemMessage(content=system_instruction),
        HumanMessage(content=user_prompt)
    ]
    
    # 4. Invoke LLM with structured output schema
    structured_llm = gemini_flash_lite.with_structured_output(PlannerOutput)
    response: PlannerOutput = structured_llm.invoke(messages)
    
    # 5. Return state updates, saving resolved/inferred difficulty back to state
    return {
        "goals": response.goals,
        "difficulty": response.inferred_difficulty
    }
