"""
What: Defines the Goal entity.
Why: Represents a specific evaluation area generated by question-maker-agent for an interview.
Boundaries: Structured criteria are stored as JSONB to pass directly to agents; no parsing logic here.
"""

import uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Float, Boolean, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB
from app.models.base import Base

class Goal(Base):
    __tablename__ = "goals"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    # goal_ref is the string like "g_01" used by agents in JSON payloads
    goal_ref: Mapped[str] = mapped_column(String(50), nullable=False)
    interview_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("interviews.id"), nullable=False, index=True)
    
    topic: Mapped[str] = mapped_column(String(255), nullable=False)
    goal: Mapped[str] = mapped_column(Text, nullable=False)
    
    passing_criteria: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    pushback_triggers: Mapped[list[dict]] = mapped_column(JSONB, nullable=False, default=list)
    wrong_answer_signals: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    references: Mapped[list[dict]] = mapped_column(JSONB, nullable=False, default=list)
    
    grounding_theory: Mapped[str] = mapped_column(Text, nullable=True)
    suggested_opening: Mapped[str] = mapped_column(Text, nullable=True)
    
    weight: Mapped[float] = mapped_column(Float, default=1.0)
    gating: Mapped[bool] = mapped_column(Boolean, default=False)
    
    # Relationships
    interview = relationship("Interview")
