"""drop gating

Revision ID: 50a0f02da45e
Revises: e5f678a12b34
Create Date: 2026-09-20 16:47:14.979504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a0f02da45e'
down_revision: Union[str, Sequence[str], None] = 'e5f678a12b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'gating')
    op.add_column('transcripts', sa.Column('progression_override', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'progression_override')
    op.add_column('goals', sa.Column('gating', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
