"""Initial schema

Revision ID: b28664c06620
Revises: 
Create Date: 2026-08-17 14:06:47.800004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28664c06620'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('num_goals', sa.Integer(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('domain_hint', sa.String(length=100), nullable=True),
    sa.Column('communication_weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_creator_id'), 'interviews', ['creator_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('room_token', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_interview_id'), 'candidates', ['interview_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_ref', sa.String(length=50), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('passing_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pushback_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wrong_answer_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding_theory', sa.Text(), nullable=True),
    sa.Column('suggested_opening', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('gating', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_interview_id'), 'goals', ['interview_id'], unique=False)
    op.create_table('candidate_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('overall_confidence', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('raw_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grader_version', sa.String(length=50), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_reports_candidate_id'), 'candidate_reports', ['candidate_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('trigger_matched', sa.String(length=255), nullable=True),
    sa.Column('flag_for_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_candidate_id'), 'transcripts', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_transcripts_created_at'), 'transcripts', ['created_at'], unique=False)
    op.create_index(op.f('ix_transcripts_goal_id'), 'transcripts', ['goal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_goal_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_created_at'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_candidate_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_candidate_reports_candidate_id'), table_name='candidate_reports')
    op.drop_table('candidate_reports')
    op.drop_index(op.f('ix_goals_interview_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_candidates_interview_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_interviews_creator_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
